---
# tasks file for update

#- name: pfSense update by package E.g pfSense-pkg-squid 
#  shell: pkg upgrade pfSense-pkg-squid

#- name: pfSense update - repo update
#  shell: pkg update
  
#- name: pfSense update - system update
#  shell: pkg upgrade -y


